#ifndef MQTTRPCCLIENTQT_GLOBAL_H
#define MQTTRPCCLIENTQT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MQTTRPCCLIENTQT_LIBRARY)
#  define MQTTRPCCLIENTQTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MQTTRPCCLIENTQTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MQTTRPCCLIENTQT_GLOBAL_H
